clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      skip_verify: true
pipeline:
  deploy-machines:
    image: docker.io/almalinux
    commands:
      - eval $AUTH_COMMAND
      - eval $DEPLOY_COMMAND
    secrets: [AUTH_COMMAND, DEPLOY_COMMAND]