- name: Install borg
  package:
    name: borgbackup
    state: latest
  become: true
  
#- name: setup repository

#- name: configure retention policy

- name: copy script
  copy:
    src: pango-backup.bash
    dest: /usr/local/bin/pango-backup.bash
    mode: "755"
  become: true

- name: copy systemd files 
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  become: true
  with_items:
  - pango-backup.service
  - pango-backup.timer

- name: enable backup timer
  systemd:
    name: pango-backup.timer
    state: restarted
    enabled: true
  become: true